---
title: "Nemo's Creature Data"
output:
  html_document:
    includes:
      after_body: footer.html
---

# Introduction

This is data from the SWGEmu Core3 repository. It interprets the Lua scripts and outputs them as CSV, which you can then download and import into Excel, LibreOffice, RStudio, or whatever editor you like.

This data is very lightly processed -- for example, Core3 uses a convention where effective resists are greater than 100%; here, creature resists are normalized and there are flags indicating if the resist is special or effective.

See the [GitHub repository](https://github.com/bholten/swg_creatures) for full details.

# Raw Data

This is raw data from the Core3 mobile scripts. It is very lightly cleaned and intended to import into Excel, Google Docs, RStudio, and so on for your own purposes. It is also appropriate for importing into a database, such as SQLite. You can think of these as the raw SQL tables that a web app might be based upon.

- [Creature Data](creature_data.html) - raw creature attributes
- [Lair Data](lairs.html) - attributes of every lair in Core3
- [Lair Mobiles](lair_mobiles.html) - associates creatures with lairs, and how they spawn (mobile or boss)
- [Spawn Groups](lair_spawn_groups.html) - associates the lair with the spawn zones in which it can spawn
- [Spawn Zones](zones.html) - raw spawn zone data
- [Static Spawns](static_spawns.html) - static spawn mobiles

# Enriched Data

- [Extinct Creatures](extinct_creatures.html)  - creatures that do not appear in spawn groups or static spawns
- [Creature Index](creatures_index.html) - individual creature reports with unified data from all tables
- Work in Progress - Spawn Zone Maps
- Work in Progress - Data Workbench
- Work in Progress - Loot Tables
- Work in Progress - DNA Samples

# Historical Data

- Work in Progress - Parsed and Searchable furrycat data

## Other Work

- [Fixing BE](https://bholten.github.io/fixingbe/) for an analysis of furrycat's BE data.